### ISSUE TITLE
An issue for Obimbo's Portfolio

### ISSUE THREAD

**Issue by Blessman-Newton** [Obimbo07/Portfolio#19]
- [x] Good job 👍 on working along with the requirement.
- [x] I suggest on making your work more responsive and be able for db optimization you should use CSS to style the html element (ref line 40) instead of br tag
- [x] I suggest the h1 that should come before *a* tag to make the work more semantics

**Comment by Obimbo07** [comment]
Thanks for the notice! I have resolved it.
